// Package airflow is the Airflow adapter (ARCHITECTURE.md §4:
// airflow-webserver.airflow:8080, REST API v1). EnsureDAG follows §8.1: render
// the DAG from the canonical template and atomically write it into the shared
// RWX DAG volume (no git-sync). Trigger/status/backfill/list use the REST API.
package airflow

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"gitlab.siptory.com/ipas/control-plane/internal/adapter"
	"gitlab.siptory.com/ipas/control-plane/internal/httpx"
)

// dagTemplate is a minimal stand-in for the canonical GitLab-versioned template
// baked into the image at build (§8.1, §5.2). The real template renders the full
// raw→bronze→dims→facts→gold→clickhouse dependency graph.
const dagTemplate = `# AUTO-GENERATED by control-plane EnsureDAG — do not edit by hand.
# pipeline: {{ .Name }}  schedule: {{ .Schedule }}
from airflow import DAG
from datetime import datetime
with DAG(dag_id="ipas_pipeline_{{ .Name }}", schedule_interval="{{ .Schedule }}",
         start_date=datetime(2026, 1, 1), catchup=False) as dag:
    pass  # TODO: render §5.2 task graph for tables {{ .Tables }}
`

type Client struct {
	baseURL string
	dagsDir string // shared RWX volume mount (§8.1), e.g. /airflow-dags
	authHdr string // optional "Basic ..." header; empty when Airflow has no auth (§4)
	tmpl    *template.Template
	http    *http.Client
}

// New builds the adapter. authHeader may be "" (Airflow currently runs without
// auth_backends per §4); pass a Basic header once auth is enabled.
func New(baseURL, dagsDir, authHeader string) *Client {
	return &Client{
		baseURL: strings.TrimRight(baseURL, "/"),
		dagsDir: dagsDir,
		authHdr: authHeader,
		tmpl:    template.Must(template.New("dag").Parse(dagTemplate)),
		http:    &http.Client{Timeout: 15 * time.Second},
	}
}

func (c *Client) headers() map[string]string {
	if c.authHdr == "" {
		return nil
	}
	return map[string]string{"Authorization": c.authHdr}
}

// EnsureDAG renders the DAG and atomically writes it into the shared volume so
// the scheduler auto-discovers it (§8.1 reference implementation).
func (c *Client) EnsureDAG(ctx context.Context, spec adapter.DAGSpec) (adapter.DAGID, error) {
	var buf bytes.Buffer
	if err := c.tmpl.Execute(&buf, spec); err != nil {
		return "", fmt.Errorf("render dag: %w", err)
	}
	dagID := adapter.DAGID("ipas_pipeline_" + spec.Name)
	final := filepath.Join(c.dagsDir, string(dagID)+".py")
	tmp := final + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0o644); err != nil {
		return "", fmt.Errorf("write dag: %w", err)
	}
	if err := os.Rename(tmp, final); err != nil { // atomic: scheduler never sees a partial file
		return "", fmt.Errorf("rename dag: %w", err)
	}
	return dagID, nil
}

type dagRunReq struct {
	Conf map[string]any `json:"conf,omitempty"`
}

type dagRunResp struct {
	DAGID string `json:"dag_id"`
	RunID string `json:"dag_run_id"`
	State string `json:"state"`
	Start string `json:"start_date"`
	End   string `json:"end_date"`
}

func (c *Client) TriggerDAG(ctx context.Context, id adapter.DAGID, conf map[string]any) (adapter.RunID, error) {
	var resp dagRunResp
	url := fmt.Sprintf("%s/api/v1/dags/%s/dagRuns", c.baseURL, id)
	if err := httpx.Do(ctx, c.http, http.MethodPost, url, c.headers(), dagRunReq{Conf: conf}, &resp); err != nil {
		return "", fmt.Errorf("trigger dag: %w", err)
	}
	return adapter.RunID(resp.RunID), nil
}

func (c *Client) GetRunStatus(ctx context.Context, id adapter.DAGID, run adapter.RunID) (adapter.RunStatus, error) {
	var resp dagRunResp
	url := fmt.Sprintf("%s/api/v1/dags/%s/dagRuns/%s", c.baseURL, id, run)
	if err := httpx.Do(ctx, c.http, http.MethodGet, url, c.headers(), nil, &resp); err != nil {
		return adapter.RunStatus{}, fmt.Errorf("get run status: %w", err)
	}
	return adapter.RunStatus{
		ID:     resp.RunID,
		DAG:    resp.DAGID,
		Start:  hhmm(resp.Start),
		Status: mapState(resp.State),
	}, nil
}

// Backfill triggers a run carrying the date range in conf; the §5.2 DAG honours
// it. (Airflow's native backfill is CLI-only; control-plane triggers a run.)
func (c *Client) Backfill(ctx context.Context, id adapter.DAGID, from, to string) (adapter.RunID, error) {
	return c.TriggerDAG(ctx, id, map[string]any{"backfill_from": from, "backfill_to": to})
}

type taskInstancesResp struct {
	TaskInstances []struct {
		DAGID    string  `json:"dag_id"`
		TaskID   string  `json:"task_id"`
		Start    string  `json:"start_date"`
		Duration float64 `json:"duration"`
		State    string  `json:"state"`
		TryNum   int     `json:"try_number"`
	} `json:"task_instances"`
}

// ListRuns returns recent task instances across all DAGs (Monitoring page),
// ordered by most-recent start.
func (c *Client) ListRuns(ctx context.Context, limit int) ([]adapter.RunStatus, error) {
	if limit <= 0 {
		limit = 50
	}
	var resp taskInstancesResp
	// Airflow 2.7.3's task-instances list endpoint does NOT accept order_by, so
	// fetch then sort client-side by start_date descending (RFC3339 sorts
	// chronologically as strings).
	url := fmt.Sprintf("%s/api/v1/dags/~/dagRuns/~/taskInstances?limit=%d", c.baseURL, limit)
	if err := httpx.Do(ctx, c.http, http.MethodGet, url, c.headers(), nil, &resp); err != nil {
		return nil, fmt.Errorf("list runs: %w", err)
	}
	sort.SliceStable(resp.TaskInstances, func(i, j int) bool {
		return resp.TaskInstances[i].Start > resp.TaskInstances[j].Start
	})
	out := make([]adapter.RunStatus, 0, len(resp.TaskInstances))
	for i, ti := range resp.TaskInstances {
		status := mapState(ti.State)
		if ti.TryNum > 1 && (ti.State == "up_for_retry" || ti.State == "running") {
			status = "Retrying"
		}
		out = append(out, adapter.RunStatus{
			ID:     fmt.Sprintf("%s.%s.%d", ti.DAGID, ti.TaskID, i),
			DAG:    ti.DAGID,
			Task:   ti.TaskID,
			Start:  hhmm(ti.Start),
			Dur:    dur(ti.Duration),
			Status: status,
		})
	}
	return out, nil
}

// PauseDAG toggles a DAG's paused flag via PATCH /api/v1/dags/{id}.
func (c *Client) PauseDAG(ctx context.Context, id adapter.DAGID, paused bool) error {
	url := fmt.Sprintf("%s/api/v1/dags/%s?update_mask=is_paused", c.baseURL, id)
	body := map[string]any{"is_paused": paused}
	if err := httpx.Do(ctx, c.http, http.MethodPatch, url, c.headers(), body, nil); err != nil {
		return fmt.Errorf("pause dag: %w", err)
	}
	return nil
}

type dagsListResp struct {
	DAGs []struct {
		DAGID        string `json:"dag_id"`
		ScheduleItvl any    `json:"schedule_interval"`
	} `json:"dags"`
}

// ListDAGIDs returns DAG ids, preferring IPAS pipeline DAGs.
func (c *Client) ListDAGIDs(ctx context.Context) ([]string, error) {
	var resp dagsListResp
	url := fmt.Sprintf("%s/api/v1/dags?limit=100", c.baseURL)
	if err := httpx.Do(ctx, c.http, http.MethodGet, url, c.headers(), nil, &resp); err != nil {
		return nil, fmt.Errorf("list dags: %w", err)
	}
	out := make([]string, 0, len(resp.DAGs))
	for _, d := range resp.DAGs {
		out = append(out, d.DAGID)
	}
	return out, nil
}

type tasksResp struct {
	Tasks []struct {
		TaskID           string   `json:"task_id"`
		DownstreamTaskID []string `json:"downstream_task_ids"`
	} `json:"tasks"`
}

type dagRunsResp struct {
	DAGRuns []struct {
		RunID string `json:"dag_run_id"`
		State string `json:"state"`
		Start string `json:"start_date"`
	} `json:"dag_runs"`
}

// GetDAG returns the task dependency graph plus the latest run's per-task status
// and recent run states. Empty dagID resolves to the first available DAG.
func (c *Client) GetDAG(ctx context.Context, dagID string) (adapter.DAGGraph, error) {
	if dagID == "" {
		ids, err := c.ListDAGIDs(ctx)
		if err != nil {
			return adapter.DAGGraph{}, err
		}
		dagID = pickIPASDag(ids)
		if dagID == "" {
			return adapter.DAGGraph{DAGID: ""}, nil
		}
	}

	// Tasks + downstream edges.
	var tr tasksResp
	if err := httpx.Do(ctx, c.http, http.MethodGet,
		fmt.Sprintf("%s/api/v1/dags/%s/tasks", c.baseURL, dagID), c.headers(), nil, &tr); err != nil {
		return adapter.DAGGraph{}, fmt.Errorf("dag tasks: %w", err)
	}

	// Recent runs (newest first from API) -> reverse to newest-last for the strip.
	var rr dagRunsResp
	_ = httpx.Do(ctx, c.http, http.MethodGet,
		fmt.Sprintf("%s/api/v1/dags/%s/dagRuns?order_by=-start_date&limit=10", c.baseURL, dagID),
		c.headers(), nil, &rr)
	recent := make([]string, 0, len(rr.DAGRuns))
	for i := len(rr.DAGRuns) - 1; i >= 0; i-- {
		recent = append(recent, nodeState(rr.DAGRuns[i].State))
	}

	// Latest run's task-instance states.
	statusByTask := map[string]string{}
	if len(rr.DAGRuns) > 0 {
		latest := rr.DAGRuns[0].RunID
		var ti taskInstancesResp
		if err := httpx.Do(ctx, c.http, http.MethodGet,
			fmt.Sprintf("%s/api/v1/dags/%s/dagRuns/%s/taskInstances", c.baseURL, dagID, latest),
			c.headers(), nil, &ti); err == nil {
			for _, t := range ti.TaskInstances {
				statusByTask[t.TaskID] = nodeState(t.State)
			}
		}
	}

	g := adapter.DAGGraph{DAGID: dagID, RecentRuns: recent}
	for _, t := range tr.Tasks {
		st := statusByTask[t.TaskID]
		if st == "" {
			st = "queued"
		}
		g.Tasks = append(g.Tasks, adapter.DAGTask{
			ID:         t.TaskID,
			Label:      t.TaskID,
			Status:     st,
			Downstream: t.DownstreamTaskID,
		})
	}
	return g, nil
}

// nodeState maps an Airflow state to the front-end node color states.
func nodeState(s string) string {
	switch strings.ToLower(s) {
	case "success":
		return "success"
	case "running":
		return "running"
	case "failed", "upstream_failed":
		return "failed"
	default:
		return "queued"
	}
}

// pickIPASDag prefers a DAG whose id looks like the IPAS ETL pipeline.
func pickIPASDag(ids []string) string {
	for _, id := range ids {
		l := strings.ToLower(id)
		if strings.Contains(l, "etl") || strings.Contains(l, "ipas") || strings.Contains(l, "qms") {
			return id
		}
	}
	if len(ids) > 0 {
		return ids[0]
	}
	return ""
}

func mapState(s string) string {
	switch strings.ToLower(s) {
	case "success":
		return "Success"
	case "running":
		return "Running"
	case "failed":
		return "Failed"
	case "up_for_retry", "restarting":
		return "Retrying"
	case "queued", "scheduled", "up_for_reschedule":
		return "Queued"
	case "":
		return "Queued"
	default:
		return capitalize(s)
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func hhmm(iso string) string {
	t, err := time.Parse(time.RFC3339, iso)
	if err != nil {
		return iso
	}
	return t.Format("15:04")
}

func dur(seconds float64) string {
	if seconds <= 0 {
		return "running"
	}
	s := int(seconds)
	return fmt.Sprintf("%dm %02ds", s/60, s%60)
}
