/* Icon registry — maps the prototype's kebab icon names to
   @carbon/icons-react components so pages can keep using
   <Icon name="data--base" size={16} />. */
import {
  Dashboard, DataBase, Code, Folder, ChartLine, Settings, Notification, Help,
  ChevronLeft, ChevronRight, ChevronDown, ChevronUp, ChevronSort, Search as SearchIcon,
  ArrowRight, ArrowLeft, UserAvatar, Time, Add, Grid, List, Filter, Save,
  Restart, Renew, View, ViewOff, Share, Send, Play, Pause, Close, Checkmark,
  OverflowMenuVertical, Document, Export, Download, ZoomIn, ZoomOut, Maximize,
  Edit, Launch, Locked, Interactions, Cloud, Analytics, ChartBar, Watson,
  ErrorFilled, CheckmarkFilled, WarningFilled, Information, Logout, User,
  Home, Flow, Terminal, UserFollow, WarningAltFilled, WarningAlt, Chat,
  Mobile, Laptop, Security, SettingsAdjust, Keyboard, Enterprise, Screen,
  Translate, Api, StarFilled, Star, Copy, InformationFilled, ArrowUp, Idea,
  Apps, Warning, Subtract, TrashCan, Unlocked, PlayOutline, StopOutline,
  ErrorOutline, Calendar, Minimize, Map,
} from '@carbon/icons-react';

const REGISTRY = {
  dashboard: Dashboard,
  'data--base': DataBase,
  code: Code,
  folder: Folder,
  'chart--line': ChartLine,
  'chart--bar': ChartBar,
  map: Map,
  settings: Settings,
  notification: Notification,
  help: Help,
  'chevron--left': ChevronLeft,
  'chevron--right': ChevronRight,
  'chevron--down': ChevronDown,
  'chevron--up': ChevronUp,
  'chevron--sort': ChevronSort,
  search: SearchIcon,
  'arrow--right': ArrowRight,
  'arrow--left': ArrowLeft,
  'user--avatar': UserAvatar,
  time: Time,
  add: Add,
  grid: Grid,
  list: List,
  filter: Filter,
  save: Save,
  restart: Restart,
  renew: Renew,
  view: View,
  'view--off': ViewOff,
  share: Share,
  send: Send,
  play: Play,
  pause: Pause,
  close: Close,
  checkmark: Checkmark,
  'overflow-menu--vertical': OverflowMenuVertical,
  document: Document,
  export: Export,
  download: Download,
  'zoom--in': ZoomIn,
  'zoom--out': ZoomOut,
  maximize: Maximize,
  edit: Edit,
  launch: Launch,
  locked: Locked,
  interactions: Interactions,
  cloud: Cloud,
  analytics: Analytics,
  watson: Watson,
  'error--filled': ErrorFilled,
  'checkmark--filled': CheckmarkFilled,
  'warning--filled': WarningFilled,
  information: Information,
  'information--filled': InformationFilled,
  logout: Logout,
  user: User,
  home: Home,
  flow: Flow,
  terminal: Terminal,
  'user--follow': UserFollow,
  'warning--alt--filled': WarningAltFilled,
  'warning--alt': WarningAlt,
  chat: Chat,
  mobile: Mobile,
  laptop: Laptop,
  security: Security,
  'settings--adjust': SettingsAdjust,
  keyboard: Keyboard,
  'help-desk': Help,
  enterprise: Enterprise,
  screen: Screen,
  translate: Translate,
  api: Api,
  'star--filled': StarFilled,
  star: Star,
  copy: Copy,
  'arrow--up': ArrowUp,
  idea: Idea,
  apps: Apps,
  warning: Warning,
  subtract: Subtract,
  'trash-can': TrashCan,
  unlocked: Unlocked,
  'play--outline': PlayOutline,
  'stop--outline': StopOutline,
  'error--outline': ErrorOutline,
  calendar: Calendar,
  minimize: Minimize,
};

export default function Icon({ name, size = 16, className, style }) {
  const Cmp = REGISTRY[name] || Document;
  return <Cmp size={size} className={className} style={style} />;
}

/* Returns the raw icon component for Carbon's `renderIcon` prop. */
export function iconFor(name) {
  return REGISTRY[name] || Document;
}
